export const subjectsList = [
    'Art',
    'Citizenship',
    'Geography',
    'History',
    'French',
    'German',
    'Literacy',
    'Music',
    'Natural history',
    'Science',
    'Arithmetic',
    'Physical education',
];
export enum subjectsEnum {
    'Art',
    'Citizenship',
    'Geography',
    'History',
    'French',
    'German',
    'Literacy',
    'Music',
    'Natural history',
    'Science',
    'Arithmetic',
    'Physical education',
}
